#!/bin/bash
# this is just for me (project maintainer) to automatically make the
# package.  don't forget to rename the root package directory to 'rr',
# if it isnt already.

# start script.
NOCOLOR=1
CMPTIME=`date "+%Y\/%m\/%d %T %Z"`
LSMTIME=`date "+%Y-%m-%d"`
VERSION=`cat version | grep -v "#"`

rm -f rr-*
cd ..
make clean 1>/dev/null 2>&1
echo $VERSION>VERSION
sed "s/%VERSION%/$VERSION/g;s/%CMPTIME%/$CMPTIME/g" rr.h.in>rr.h
sed "s/%VERSION%/$VERSION/g;s/%GZSIZE%/0 rr-${VERSION}.tar.gz/g;s/%BZ2SIZE%/0 rr-${VERSION}.tar.bz2/g;s/%LSMTIME%/$LSMTIME/g;" rr.lsm.in>rr.lsm
md5sum * 1>MD5SUM 2>/dev/null
touch *
cd ..
mv rr rr-${VERSION}
tar -c rr-${VERSION}/>/tmp/rr-${VERSION}.tar
gzip /tmp/rr-${VERSION}.tar
tar -c rr-${VERSION}/>/tmp/rr-${VERSION}.tar
bzip2 /tmp/rr-${VERSION}.tar
# doesn't effect the packaged version from here on.
mv rr-${VERSION} rr
mv /tmp/rr-${VERSION}.* rr/adm/ 
cd rr/adm
GZSIZE=`wc -c rr-${VERSION}.tar.gz|awk {'print $1'}`
BZ2SIZE=`wc -c rr-${VERSION}.tar.bz2|awk {'print $1'}`
sed "s/%VERSION%/$VERSION/g;s/%GZSIZE%/$GZSIZE rr-${VERSION}.tar.gz/g;s/%BZ2SIZE%/$BZ2SIZE rr-${VERSION}.tar.bz2/g;s/%LSMTIME%/$LSMTIME/g" ../rr.lsm.in>../rr.lsm
